# Generated by Django 5.0.4 on 2024-04-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_productproxy_options_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/products/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
